spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ceos_everytime_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: jeonmin7721
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

logging:
  level:
    org.hibernate.SQL: debug
  #  org.hibernate.type: trace

file:
  dir: E:\ceos-study\everytime\attachment_file\